/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-07-15 12:13:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_005fof_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Encore Tours</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 링크 순서 중요합니다. <<< 4조, 순서 지켜주세용 -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<footer class=\"footer text-center\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Footer Location -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase mb-4\">Location</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead mb-0\">\r\n");
      out.write("\t\t\t\t\t\tSeocho 1(il)-dong, Seocho-gu, Seoul <br>335 Hyoryeong-ro\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Footer Social Icons -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase mb-4\">SHARE</h4>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-outline-light btn-social mx-1\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-facebook-f\"></i>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fab fa-fw fa-linkedin-in\"></i>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Footer About Text -->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-uppercase mb-4\">About Encore Tours</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"lead mb-0\">\r\n");
      out.write("\t\t\t\t\t\t설명설명설명설명설명설명 <br />\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">Start Encore Tours</a>.\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Copyright Section -->\r\n");
      out.write("\t<section class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<small>Copyright &copy; Encore Tours 2019</small>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 하기 링크 위치 고정 (body 가장 하단에) -->\r\n");
      out.write("\t<!-- Plugin JavaScript -->\r\n");
      out.write("\t<script src=\"/team4_jeju/resources/js/jquery.easing_gyubeom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Contact Form JavaScript -->\r\n");
      out.write("\t<script src=\"/team4_jeju/resources/js/jqBootstrapValidation_gyubeom.js\"></script>\r\n");
      out.write("\t<script src=\"/team4_jeju/resources/js/contact_me_gyubeom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom scripts for this template -->\r\n");
      out.write("\t<script src=\"/team4_jeju/resources/js/main_nav_gyubeom.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
